# Generated by Django 4.1 on 2022-08-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(default=None, upload_to='songs'),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
